### ISSUE TITLE
BaseURL returns 404

### ISSUE THREAD

**Issue by tvOSPopcorn** [a-ignatov-parc/tvos-soap4.me#2]
Hai, after compiling your application i'm returned with an error once opening the application,

```
Error Launching Application
TVMLKITErrorDomain 3
```

I also saw that the [BaseURL](https://a-ignatov-parc.github.io/tvos-soap4.me-releases/1.0.0/) points to a 404 error, any advice? thanks!

**Comment by a-ignatov-parc** [comment]
Hi there. To fully test application you also need to build and run TVJS app.

Here is a short instruction on how to do this.

In project folder run next commands:
```bash
npm install
gulp serve
```

If you don't have globally installed `gulpjs` then before executing second command run 
```bash
npm install -g gulp
```

P.S. App was tested in nodejs 4.4.x and npm 2.15.x

**Comment by a-ignatov-parc** [comment]
Also to pass login screen you will need premium (payed) account on https://soap4.me/

**Comment by a-ignatov-parc** [comment]
Also you can build application in Release mode and use prebuild version from [tvos-soap4.me-releases](https://github.com/a-ignatov-parc/tvos-soap4.me-releases)

![screen shot 2016-08-13 at 23 43 32](https://cloud.githubusercontent.com/assets/347650/17645509/eb19147e-61b0-11e6-9582-85680534738f.png)

**Comment by a-ignatov-parc** [comment]
> Also to pass login screen you will need premium (payed) account on https://soap4.me/

Today I made a closer look at second version of soap4.me api. And it has ability to work with major features without having premium account. Will update app in few days.

**Comment by hessius** [comment]
Great! Looking forward to it as I don't currently have a paid account :)

**Comment by a-ignatov-parc** [comment]
Yeah. I understand :)
